name: Black Formatting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check src with Black
        uses: psf/black@stable
        with:
          src: "./src"
      - name: Check tests with Black
        uses: psf/black@stable
        with:
          src: "./tests"
