name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      -
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Run tests and collect coverage
        run: pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3