name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  pyodbc_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc

      - name: Check drivers
        run:
          python
          import pyodbc
          assert isinstance(pyodbc.drivers(), list)
