name: pyodbc-tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  pyodbc_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc

      - name: Check drivers
        run:
          python -c "import pyodbc; assert isinstance(pyodbc.drivers(), list)"
