name: Sphinx build test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
#    - uses: ammaraskar/sphinx-action@master
#      with:
#        docs-folder: "docs/"
    # Example of using a custom build-command.
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . build"
        docs-folder: "docs2/"
