name: Sphinx build test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
#    - uses: ammaraskar/sphinx-action@master
#      with:
#        docs-folder: "docs/"
    # Example of using a custom build-command.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        sphinx-build -M html docs/ docs/build
#    - uses: ammaraskar/sphinx-action@master
#      with:
#        build-command: "sphinx-build -b html . build"
#        docs-folder: "docs/"
