name: Sphinx build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: "Build sphinx"
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        sphinx-build -M html docs/ docs/build
        

